steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', './src/go-hpa']
    env: ['GOPATH=.']

  - name: 'gcr.io/cloud-builders/go'
    args: ['test', 'go-hpa']
    env: ['GOPATH=.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/lms-go-hpa', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=iugmali/lms-go-hpa', '.']